resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml

parameter_defaults:
  # This sets 'external_network_bridge' in l3_agent.ini to an empty string
  # so that external networks act like provider bridge networks (they
  # will plug into br-int instead of br-ex)
  NeutronExternalNetworkBridge: "''"
parameter_defaults:
  InternalApiNetCidr: 172.16.0.0/16
  TenantNetCidr: 172.17.0.0/16
  StorageNetCidr: 172.18.0.0/16
  StorageMgmtNetCidr: 172.19.0.0/16
  StorageMgmtNetCidr: 172.19.0.0/16
  ManagementNetCidr: 172.20.0.0/16
  ExternalNetCidr: 10.2.4.0/21
  InternalApiAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.5.200'}]
  TenantAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.5.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.5.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.5.200'}]
  ManagementAllocationPools: [{'start': '172.20.0.10', 'end': '172.20.5.200'}]
  # Leave room for floating IPs in the External allocation pool
  ExternalAllocationPools: [{'start': '10.2.4.10', 'end': '10.2.5.55'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 10.2.0.1
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.0.0.1
  # The IP address of the EC2 metadata server. Generally the IP of the Undercloud
  EC2MetadataIp: 192.0.0.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["8.8.8.8","8.8.4.4"]
  InternalApiNetworkVlanID: 162
  StorageNetworkVlanID: 163
  StorageMgmtNetworkVlanID: 164
  TenantNetworkVlanID: 165
  ManagementNetworkVlanID: 166
  ExternalNetworkVlanID: 7
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  NeutronExternalNetworkBridge: "''"
  # Customize bonding options if required
  BondInterfaceOvsOptions:
    "bond_mode=balance-tcp"
